### PR TITLE
Changed button style

### PR DESCRIPTION
**Pull request by Illuminati9**
Solved issue #3 . Added button style to button in main page.

### CODE REVIEW

**Comment by orbitalmartian8** [comment]
@Illuminati9 This is awesome, could you add a hover effect please? :)

**Comment by Illuminati9** [comment]
Hey @orbitalmartian8 , I have also added hover effect and made cursor to pointer when hovered.

**Comment by orbitalmartian8** [comment]
Looks good from my iPad, just going to check the hover on my PC then it'll probably be a merge :)

**Comment by orbitalmartian8** [comment]
Works amazing, if you're happy, this can be merged now.

**Pull request merged**
